"""M03 acceptance: deterministic, reversible migrations with a drift gate.

All tests are synchronous on purpose: Alembic's env.py drives its own
event loop, so these run it from plain functions and use ``asyncio.run``
for direct SQL assertions.
"""

import asyncio
import time
from datetime import UTC, datetime

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import text
from sqlalchemy.exc import DBAPIError
from sqlalchemy.ext.asyncio import create_async_engine
from testcontainers.postgres import PostgresContainer

from atlas.shared.ids import uuid7
from tests.integration.dbtools import alembic_config, alembic_env, list_public_tables

pytestmark = pytest.mark.integration

EXPECTED_TABLES = {
    "users",
    "workspaces",
    "sources",
    "documents",
    "document_versions",
    "chunks",
    "ingestion_jobs",
    "settings",
    "feature_flags",
    "audit_events",
}
UPGRADE_BUDGET_SECONDS = 30.0


def test_upgrade_from_empty_then_downgrade_to_base_then_up_again(
    fresh_database_url: str,
) -> None:
    with alembic_env(fresh_database_url) as config:
        started = time.perf_counter()
        command.upgrade(config, "head")
        elapsed = time.perf_counter() - started
        assert elapsed <= UPGRADE_BUDGET_SECONDS, f"upgrade took {elapsed:.1f}s"

        tables = asyncio.run(list_public_tables(fresh_database_url))
        assert tables >= EXPECTED_TABLES
        assert "audit_events_default" in tables  # the backstop partition

        command.downgrade(config, "base")
        tables_after = asyncio.run(list_public_tables(fresh_database_url))
        assert tables_after == {"alembic_version"}, "downgrade must return to empty"

        command.upgrade(config, "head")
        assert asyncio.run(list_public_tables(fresh_database_url)) >= EXPECTED_TABLES


def test_exactly_one_head(postgres_container: PostgresContainer) -> None:
    script = ScriptDirectory.from_config(alembic_config(postgres_container.get_connection_url()))
    assert len(script.get_heads()) == 1


def test_models_and_migrations_do_not_drift(migrated_database_url: str) -> None:
    """M03 risk mitigation: autogenerate against a migrated DB must find
    nothing to do. A nonempty diff fails the build."""
    with alembic_env(migrated_database_url) as config:
        try:
            command.check(config)
        except AutogenerateDiffsDetected as diff:
            pytest.fail(f"model/migration drift detected: {diff}")


def test_audit_events_rejects_update_and_delete(migrated_database_url: str) -> None:
    """M03 acceptance: UPDATE or DELETE on audit_events raises at the DB level."""

    async def scenario() -> None:
        engine = create_async_engine(migrated_database_url)
        try:
            async with engine.begin() as connection:
                await connection.execute(
                    text(
                        "INSERT INTO audit_events"
                        " (id, workspace_id, actor, event_type, subject_type, created_at)"
                        " VALUES (:id, :ws, 'system', 'test.event', 'test', :now)"
                    ),
                    {"id": uuid7(), "ws": uuid7(), "now": datetime.now(UTC)},
                )
            with pytest.raises(DBAPIError, match="append-only"):
                async with engine.begin() as connection:
                    await connection.execute(text("UPDATE audit_events SET actor = 'tampered'"))
            with pytest.raises(DBAPIError, match="append-only"):
                async with engine.begin() as connection:
                    await connection.execute(text("DELETE FROM audit_events"))
            async with engine.connect() as connection:
                count = await connection.execute(text("SELECT count(*) FROM audit_events"))
                assert count.scalar_one() == 1
        finally:
            await engine.dispose()

    asyncio.run(scenario())
